# coding: utf-8

"""
    Environmental Exposures API

    API for environmental exposure models for NIH Data Translator program

    OpenAPI spec version: 1.0.0
    Contact: stealey@renci.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import exposures_api
from exposures_api.rest import ApiException
from exposures_api.models.coordinate import Coordinate


class TestCoordinate(unittest.TestCase):
    """ Coordinate unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCoordinate(self):
        """
        Test Coordinate
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = exposures_api.models.coordinate.Coordinate()
        pass


if __name__ == '__main__':
    unittest.main()
